print('-------------------------------------')
print('Calculadora de média de 5 números')
num1 = float(input('Digite o número 1: '))
num2 = float(input('Digite o número 2: '))
num3 = float(input('Digite o número 3: '))
num4 = float(input('Digite o número 4: '))
num5 = float(input('Digite o número 5: '))
print(f'A média dos números digitados é {(num1 + num2 + num3 + num4 + num5) / 5}')
print('-------------------------------------')
